version: '3.8'
services:
  mock-front-app:
    image: mock-front:production
    depends_on: 
        - mock-back-app
    ports:
      - 80:80
    networks:
      - common-network
  mock-back-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mock-mysql-container
      - mock-redis-container
    ports:
      - 3004:3004
    networks:
      - common-network
  mock-mysql-container:
    image: mysql
    ports: 
      - 3306:3306
    volumes:
      - /User/Languiyuan/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mock_system
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  mock-redis-container:
    image: redis
    ports: 
      - 6379:6379
    volumes:
      - /User/Languiyuan/redis-data:/data
      # - E:\\FrontEnd\\项目\\nestjs\\docker\\redis\\conf\\redis.conf:/usr/local/etc/redis/redis.conf
    # command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
