version: '3.8'
services:
  mock-front-app:
    image: mock-front:production
    depends_on: 
        - mock-back-app
    ports:
      - 9704:9704
    networks:
      - common-network
  mock-back-app:
    image: mock-back:production
    depends_on:
      - mysql3307
      - redis6380
    ports:
      - 4399:4399
    networks:
      - common-network
  mysql3307:
    image: mysql
    ports: 
      - 3307:3306
    volumes:
      # - /User/Languiyuan/mysql-data:/var/lib/mysql
      - E:\\FrontEnd\\项目\\nestjs\\mysql-test:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mock_system
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  redis6380:
    image: redis
    ports: 
      - 6380:6379
    volumes:
      # - /User/Languiyuan/redis-data:/data
      - E:\\FrontEnd\\项目\\nestjs\\redis-test:/data
      # - E:\\FrontEnd\\项目\\nestjs\\docker\\redis\\conf\\redis.conf:/usr/local/etc/redis/redis.conf
    # command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
