version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - CACHEBUST=$(date +%s)
    depends_on:
      - mock-mysql-container
      - mock-redis-container
    ports:
      - 3004:3004
    networks:
      - common-network
  mock-mysql-container:
    image: mysql
    volumes:
      - /User/Languiyuan/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mock_system
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  mock-redis-container:
    image: redis
    volumes:
      -  /User/Languiyuan/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
